services:
  mongodb:
    image: mongo:7.0
    container_name: orillusive-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - orillusive_mongo_data:/data/db

volumes:
  orillusive_mongo_data:
